version: "2.4"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data/mongo:/data/db
    restart: unless-stopped
    # command: mongod --verbose

  mongo-express:
    image: mongo-express:latest
    ports:
      - 9002:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin123"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "admin"
      ME_CONFIG_MONGODB_SERVER: "mongo"
    depends_on:
      - mongo
    restart: unless-stopped